### ISSUE TITLE
UART protocol description

### ISSUE THREAD

**Issue by spacie2136** [roccotsi2/esp32-smart-bms-simulation#1]
I will attach protocol description with english translation.

Im also looking into because i want to read out informations en publish to MQTT.

[Part 4_ Daly RS485+UART Protocol.pdf](https://github.com/roccotsi2/esp32-smart-bms-simulation/files/6289643/Part.4_.Daly.RS485%2BUART.Protocol.pdf)

**Comment by roccotsi2** [comment]
Hi,

thank you for this documentation, but I think this is for another Smart BMS from Daly. The one I want to use has not a fixed data length (as it is the case in the documentation).
